name: Our First Workflow
on: push
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello, GitHub Actions!'
  pwd-ls:
    name: PWD & LS
    runs-on: ubuntu-latest
    steps:
      - name: PWD
        run: pwd
      - name: Check NPM Version
        run: npm --version
