name: Our First Workflow
on: push
jobs:
  node-install:
    name: Node Install
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.10
  pwd-ls:
    name: PWD & LS
    runs-on: ubuntu-latest
    steps:
      - name: PWD
        run: pwd
      - name: list file
        run: ls -alh /home/runner/work/react-vite-playground/react-vite-playground/
      - name: change directory
        run: cd /home/runner/work/react-vite-playground/react-vite-playground/
      - name: Check NPM Version
        run: npm --version
      - name: Install Packages
        run: npm i
